image: node:20

stages:
  - install
  - release
  - deploy

variables:
  GITLAB_TOKEN: $GITLAB_TOKEN

install:
  stage: install
  script:
    - npm ci

release:
  stage: release
  script:
    - npx semantic-release
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish
  environment: production
  only:
    - main
